services:

  # nginx
  web:
    container_name: simple-form-web
    restart: unless-stopped

    image: nginx:1.25.5
    ports:
      - "80:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ../:/var/www

  # php
  app:
    container_name: simple-form-app
    restart: unless-stopped

    build:
      dockerfile: php/Dockerfile
    working_dir: /var/www
    volumes:
      - ../:/var/www

  # mysql
  db:
    container_name: simple-form-db
    restart: unless-stopped

    image: mysql:8.0
    volumes:
      - mysql-data:/var/lib/mysql;
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_USER: user
      MYSQL_PASSWORD: secret
      MYSQL_DATABASE: form-app

volumes:
  mysql-data: